CREATE DATABASE node_crud;
USE node_crud;
CREATE TABLE users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (100),
    email VARCHAR(100)
);

USE node_crud;

/*CREACION DE TABLA PARA EL LOGIN*/
CREATE TABLE login_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);